name: Deploy to Surge

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      run: surge ./ https://Pablo-2023-0194.surge.sh
      env:
        SURGE_TOKEN: ${{ a30010ff426f3b1e6b213f284b7b0b8a }}
